### ISSUE TITLE
meexmachina: no-shows!

### ISSUE THREAD

**Issue by hb9dug** [cariboulabs/cariboulite#100]
For more than a month, meexmachina (David Michaeli), which seems to be the leader of the project, has not made any more contributions. 

A status report on the project, especially on the firmware and the promised basic software, seems to me a reasonable request from the people who invested in CaribouLite!

A prompt answer will be welcome

Cordialement,
Michel, HB9DUG

**Comment by gerd0355** [comment]
I agree with you. I am also waiting for more informations. 

Regards
Gerhard

**Comment by great9** [comment]
@konimaru seems to be the only guy doing updates on this codebase

**Comment by hb9dug** [comment]
I confirm, the package provided by Marco works on PiSDR. 
SDR++ must be run from sudo and  I have to open before a console and execute on it : sudo pulseaudio --system=true to have audio.
GNUradio Soapy Source block works but Sink block craches GNUradio.

Regards,
Michel

**Comment by hudouseko** [comment]
>  GNUradio Soapy Source block works but Sink block craches GNUradio.
> 

If not for other reasons as well, I'd assume Soapy sink wouldn't work because writeStream method in soapy_api doesn't seem to be implemented at all (see [https://github.com/cariboulabs/cariboulite/issues/89](url) ).

**Comment by G0MJW** [comment]
I think the project has been abandoned. Such a pity.

**Comment by G0MJW** [comment]
Interesting. Thanks.

 

Mike

**Comment by brianrusso** [comment]
I'm sure I'll get voted off the island, but let's consider that a 1-person operation designing and constructing an open source, small-scale SDR during a global chip supply chain fiasco is pretty tough.

I agree an update is in order, but let's not get our pitchforks out just yet.

I have received one, and while it has some stutter issues (presumably due to a bandwidth bottleneck somewhere) - it does technically work. Hopefully the issues are just software related and can be resolved.

$0.02

**Comment by great9** [comment]
> I'm sure I'll get voted off the island, but let's consider that a 1-person operation designing and constructing an open source, small-scale SDR during a global chip supply chain fiasco is pretty tough.
> 
> I agree an update is in order, but let's not get our pitchforks out just yet.
> 
> I have received one, and while it has some stutter issues (presumably due to a bandwidth bottleneck somewhere) - it does technically work. Hopefully the issues are just software related and can be resolved.
> 
> $0.02

for almost 2 months now

**Comment by ImDroided** [comment]
> I'm sure I'll get voted off the island, but let's consider that a 1-person operation designing and constructing an open source, small-scale SDR during a global chip supply chain fiasco is pretty tough.
> 
> I agree an update is in order, but let's not get our pitchforks out just yet.
> 
> I have received one, and while it has some stutter issues (presumably due to a bandwidth bottleneck somewhere) - it does technically work. Hopefully the issues are just software related and can be resolved.
> 
> $0.02

While I agree to a point unless the guy is dead there is no reason not to do the 30 second merge of the fixes that have been waiting 2 months in que. Like the code is done other people fixed it for you all you need to do is click merge. The sad part is is if people don't come and read the issues, they'll never know that a fix exists for the mirror issue and other stuff but if this guy would just merge the damn things, they wouldn't have to worry about it from the get-go.

**Comment by great9** [comment]
> > I'm sure I'll get voted off the island, but let's consider that a 1-person operation designing and constructing an open source, small-scale SDR during a global chip supply chain fiasco is pretty tough.
> > I agree an update is in order, but let's not get our pitchforks out just yet.
> > I have received one, and while it has some stutter issues (presumably due to a bandwidth bottleneck somewhere) - it does technically work. Hopefully the issues are just software related and can be resolved.
> > $0.02
> 
> While I agree to a point unless the guy is dead there is no reason not to do the 30 second merge of the fixes that have been waiting 2 months in que. Like the code is done other people fixed it for you all you need to do is click merge. The sad part is is if people don't come and read the issues, they'll never know that a fix exists for the mirror issue and other stuff but if this guy would just merge the damn things, they wouldn't have to worry about it from the get-go.

The owner of this repo and founder of cariboulite has interacted in the issues section when these fixes were posted.

**Comment by meexmachina** [comment]
Hi contributors, 
Indeed I was extremely unavailable in the last few months and even the easiest pull request has been neglected by me for too long. The firmware and software development is continuing, very much thanks to you.
Currently working on the TX side - I/Q transmission - firmware and software. takes time....

**Comment by brianrusso** [comment]
That's great news, glad to hear this project still has life. If you could commit (pun intended) to a regular cadence of updates, I believe that would add a lot of value for this community.
