### ISSUE TITLE
Wrong board shipped?

### ISSUE THREAD

**Issue by synthetikspace** [cariboulabs/cariboulite#108]
Did anyone else here have the wrong board shipped when ordering the 6Ghz model but instead received the SMI version?

I have reached out to David Michaeli who responded that the issue would be resolved but I have not heard back in over a month now after following up several times to no avail.

Very disappointing.

**Comment by ImDroided** [comment]
There's a thread somewhere buried in the issues page where someone was posting up pictures of their board, not even populated in the right spots or something like that. But yeah it's known that are quite a few people have gotten the wrong stuff. I don't know what they're doing to fix it though.

**Comment by K7MDL2** [comment]
Try contacting Crowdsupply support?  I believe they are doing the fulfilment and this has been acknowledged by them for some others and they arranged the swap..

**Comment by rhammock1** [comment]
Contacting crowd supply worked for me. I sent pictures of the board I got and packaging and they shipped me a new one within a week or two

**Comment by ojg78** [comment]
What are the differences (physically) between the smi and 6ghz version? I feel like it would be smart to check my freshly received board now and try to ignore the possibility that the whole project seems semi abandoned by it's originator.

**Comment by rhammock1** [comment]
The ISM version just has empty solder pads on the Mixer section at the bottom of the board and the area surrounded by the gold rectangle on top. When I got mine I thought it had missed a step in the production and was just missing some components.

**Comment by jadware** [comment]
happened to me, was an issue at their distributor.  all got sorted out after a couple weeks and have the right boards now.  just be patient, shaking out all the bugs in the process
