### ISSUE TITLE
pcb project

### ISSUE THREAD

**Issue by eljuligallego** [cariboulabs/cariboulite#11]
Hi,

would like to know if you plan to share the project pcb file (in kicad would be great).

I would like modify the design to make a more simple and cheapest project to evaluate the AT86RF215(maybe put more than one in one pcb or make them stackable for multiple channels) with the raspberry pi and most of the RF mixer part is not needed.

P.D.

From your bom the MAAM-011206-TR1000 RF amplifier is obsolete and the replace part MAAM-011206-TR3000 cost 11 euros in mouser and you use 2!! and total bom is almost 100€ on mouser(the best place i found they have all components).

Thanks,
your project is very promising, I hope you can make it to buy one.

**Comment by meexmachina** [comment]
This issue was closed as it appears twice
