### ISSUE TITLE
3 references to cariboulite_get_native_mtu_size_samples in source

### ISSUE THREAD

**Issue by jackchallen** [cariboulabs/cariboulite#119]
Looks like it’s changed to cariboulite_radio_get_native_mtu_size_samples

**Comment by alphafox02** [comment]
Step 4, main software, is now unable to compile due to the undefined reference to 'caribou lite_get_native_mtu_size_samples' as I assume as the original poster points out that call has changed.

**Comment by great9** [comment]
CaribouLite project by David Michaeli is the only project where it's users are supposed to develop the base software, drivers, firmware, fix bugs after the original author just to get it working.

**Comment by alphafox02** [comment]
Fixed in the latest push to main.
