### ISSUE TITLE
Transmit modulation types?

### ISSUE THREAD

**Issue by oldirty91** [cariboulabs/cariboulite#121]
Is this capable of transmitting any type of modulation? I.e. can I transmit FM or maybe something like c4fm? Can I feed a raw IQ for transmit? The docs for the AT86 modem chip suggest transmits certain modulation types (psk, fsk, oftm) which suggests the chip handles the modulation. What am I missing? I dug through the docs and some of the issues here and couldn’t really find an answer. Thanks.

**Comment by meexmachina** [comment]
yes the IQ can be transmitted through the I/Q interface. It is currently still buggy though and I'm working on stabilizing it.
The baseband modem contains the internal waveforms but the FPGA in cariboulite connects directly to the IQ channel which kind of bypasses everything. Then you get the "raw" data on rx and push your "raw" data in tx. which gives you the ability to create vectors of samples and push them into the modem to transmit.
