### ISSUE TITLE
Gerber files: Outline missing with some manufacturers

### ISSUE THREAD

**Issue by kenokenobingo** [cariboulabs/cariboulite#9]
[OSH Park](https://oshpark.com/) and [Aisler](https://aisler.net/) can’t process the Gerber files propers because they report a missing outline. JLC PCB doesn’t have any problems with the files, though.

<img width="560" alt="Screenshot OSH Park." src="https://user-images.githubusercontent.com/9639767/123523472-0aea6680-d6c4-11eb-9df8-a070241a4cf6.png">

<img width="699" alt="Screenshot Aisler." src="https://user-images.githubusercontent.com/9639767/123523481-1a69af80-d6c4-11eb-9ce7-90f7f9f3613f.png">

**Comment by GordonFR24** [comment]
PCBWay have similar issues

**Comment by meexmachina** [comment]
Hi @kenokenobingo and @GordonFR24 Thanks a lot,
I uploaded a new file with "cariboulite_r2.Outline" hope it helps...
please let me know it still doesn't work.

**Comment by kenokenobingo** [comment]
Thanks, @meexmachina! It’s working now with AISLER, OSH Park, and PCBWay.

**Comment by meexmachina** [comment]
Thanks for the feedback!
